<?php



function rolecall_user_login(&$edit, $account, $category = NULL) {

    $rolemap = array (
        /* 	  "role" => "htaccessgroup", */
        "damtpuser" => "damtpusers"
    );


	 foreach ($rolemap as $role => $groupname) {
	 	 //check to see if user is in groupfile
         $roleobj = user_role_load_by_name($role);
		 if ( _check_member($account->name,$groupname) !== FALSE) {
             //you are in groupname
             $iam = user_has_role($roleobj->rid);
             if ($iam) {
                 //user already in group
                 drupal_set_message(t("user in group"));
             } else {
                 // add them in
                 drupal_set_message(t("adding role to user"));
                 $roles = $account->roles + array($roleobj->rid => $role);
                 $account->original = clone $account;
                 user_save($account, array('roles' => $roles));
             }
         } else {
             //remove the role from the account!
             drupal_set_message(t("removing role from user"));
             $roles = $account->roles;
             unset($roles[$roleobj->rid]);
             $account->original = clone $account;
             user_save($account, array('roles' => $roles));
         }
         
	 }
     
}



function _check_member($username,$groupname) {
    
    $groupfile = "/webgroup_all";
    
    $ug = file(drupal_get_path('module', 'rolecall').$groupfile);
    
    
    
    foreach ($ug as $line) {
        $x = explode(":",$line);
	    if (trim ($x[0]) == $groupname) {
            $members = explode(" ",$x[1]);
            foreach($members as $name) {
                if (trim($name) == $username) {
                    return TRUE;
                }
            }
	    }
    }
    return FALSE;
}